/**
 * https://www.youtube.com/watch?v=Mm2eYfj0SgA&list=LL&index=8&t=735s
 */


let time = 0;
let wave = [];
n = 1;

function setup () {
  createCanvas(5000, 600);
}


function draw () {

  // draw canvas
  background(0);
  translate(200, 200);

  let x = 0;
  let y = 0;

  for (let i = 0; i < n; i++) {
    prevx = x;
    prevy = y;

    let n = i * 2 + 1;
    let radius =  75 * ( 4 / (n * PI));
    x += radius * cos(n * time);
    y += radius * sin(n * time);
  
    // draw circle
    stroke(255, 100);
    noFill();
    ellipse(prevx, prevy, radius * 2)

    // draw the moving dot
    stroke(255);
    line(prevx, prevy, x, y);
  }

  // draw the wave pattern generated by the points found
  wave.unshift(y);
  translate(200, 0);
  line(x - 200, y, 0, wave[0]);
  beginShape();
  noFill();
  for (let i = 0; i < wave.length; i++) {
    vertex(i, wave[i])
  }
  endShape();

  // increment the angle
  time += 0.1;

  // maintain samples that can only fit in the canvas 
}
